#
#   Copyright (c) 2014-2017 Philipp Paulweber
#   All rights reserved.
#
#   Developed by: Philipp Paulweber
#                 Emmanuel Pescosta
#                 https://github.com/ppaulweber/libstdhl
#
#   This file is part of libstdhl.
#
#   libstdhl is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   libstdhl is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with libstdhl. If not, see <http://www.gnu.org/licenses/>.
#

language: cpp

dist: trusty
sudo: required

matrix:
  include:
    - os: linux
      compiler: clang
      addons: &addons_clang_4_0
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - gcc-6
            - g++-6
            - clang-4.0
      env: ENV_CC="clang-4.0" ENV_CXX="clang++-4.0" BUILD="debug"
    - os: linux
      compiler: clang
      addons: *addons_clang_4_0
      env: ENV_CC="clang-4.0" ENV_CXX="clang++-4.0" BUILD="sanitize"
    - os: linux
      compiler: clang
      addons: *addons_clang_4_0
      env: ENV_CC="clang-4.0" ENV_CXX="clang++-4.0" BUILD="release"

    - os: linux
      compiler: clang
      addons: &addons_clang_3_9
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
          packages:
            - gcc-6
            - g++-6
            - clang-3.9
      env: ENV_CC="clang-3.9" ENV_CXX="clang++-3.9" BUILD="debug"
    - os: linux
      compiler: clang
      addons: *addons_clang_3_9
      env: ENV_CC="clang-3.9" ENV_CXX="clang++-3.9" BUILD="release"

    - os: linux
      compiler: clang
      addons: &addons_clang_3_8
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - gcc-6
            - g++-6
            - clang-3.8
      env: ENV_CC="clang-3.8" ENV_CXX="clang++-3.8" BUILD="debug"
    - os: linux
      compiler: clang
      addons: *addons_clang_3_8
      env: ENV_CC="clang-3.8" ENV_CXX="clang++-3.8" BUILD="release"

    - os: linux
      compiler: clang
      addons: &addons_clang_3_7
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - gcc-5
            - g++-5
            - clang-3.7
      env: ENV_CC="clang-3.7" ENV_CXX="clang++-3.7" BUILD="debug"
    - os: linux
      compiler: clang
      addons: *addons_clang_3_7
      env: ENV_CC="clang-3.7" ENV_CXX="clang++-3.7" BUILD="release"

    - os: linux
      compiler: gcc
      addons: &addons_gcc_6
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: "ppa:jonathonf/binutils"
          packages:
            - gcc-6
            - g++-6
            - binutils
      env: ENV_CC="gcc-6" ENV_CXX="g++-6" BUILD="debug"
    - os: linux
      compiler: gcc
      addons: *addons_gcc_6
      env: ENV_CC="gcc-6" ENV_CXX="g++-6" BUILD="sanitize"
    - os: linux
      compiler: gcc
      addons: *addons_gcc_6
      env: ENV_CC="gcc-6" ENV_CXX="g++-6" BUILD="release"

    - os: linux
      compiler: gcc
      addons: &addons_gcc_5
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
      env: ENV_CC="gcc-5" ENV_CXX="g++-5" BUILD="debug"
    - os: linux
      compiler: gcc
      addons: *addons_gcc_5
      env: ENV_CC="gcc-5" ENV_CXX="g++-5" BUILD="release"

    - os: linux
      compiler: gcc
      addons: &addons_gcc_4_9
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
      env: ENV_CC="gcc-4.9" ENV_CXX="g++-4.9" BUILD="debug"
    - os: linux
      compiler: gcc
      addons: *addons_gcc_4_9
      env: ENV_CC="gcc-4.9" ENV_CXX="g++-4.9" BUILD="release"

  allow_failures:

    - os: osx
      osx_image: xcode8
      compiler: clang

    - os: osx
      osx_image: xcode8
      compiler: gcc

install:
  - echo ${TRAVIS_OS_NAME}
  - make  --version
  - cmake --version
  - ${CC} --version
  - ${CXX} --version
  - ld --version
  - echo ${BUILD}

script:
  - make ${BUILD}-all ${BUILD}-test ${BUILD}-benchmark
